// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Subscription struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	StripeCustomerID     pgtype.Text
	StripeSubscriptionID pgtype.Text
	Plan                 string
	Status               string
	CurrentPeriodEnd     pgtype.Timestamp
	CreatedAt            pgtype.Timestamp
}
