// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    id,
    user_id,
    stripe_customer_id,
    stripe_subscription_id,
    plan,
    status,
    current_period_end
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, user_id, stripe_customer_id, stripe_subscription_id, plan, status, current_period_end, created_at
`

type CreateSubscriptionParams struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	StripeCustomerID     pgtype.Text
	StripeSubscriptionID pgtype.Text
	Plan                 string
	Status               string
	CurrentPeriodEnd     pgtype.Timestamp
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ID,
		arg.UserID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.Plan,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByUserID = `-- name: GetSubscriptionByUserID :one
SELECT id, user_id, stripe_customer_id, stripe_subscription_id, plan, status, current_period_end, created_at
FROM subscriptions
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByUserID(ctx context.Context, userID pgtype.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByUserID, userID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (
    id,
    user_id,
    stripe_customer_id,
    stripe_subscription_id,
    plan,
    status,
    current_period_end
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (user_id)
DO UPDATE SET
    stripe_customer_id = EXCLUDED.stripe_customer_id,
    stripe_subscription_id = EXCLUDED.stripe_subscription_id,
    plan = EXCLUDED.plan,
    status = EXCLUDED.status,
    current_period_end = EXCLUDED.current_period_end
RETURNING id, user_id, stripe_customer_id, stripe_subscription_id, plan, status, current_period_end, created_at
`

type UpsertSubscriptionParams struct {
	ID                   pgtype.UUID
	UserID               pgtype.UUID
	StripeCustomerID     pgtype.Text
	StripeSubscriptionID pgtype.Text
	Plan                 string
	Status               string
	CurrentPeriodEnd     pgtype.Timestamp
}

func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.ID,
		arg.UserID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.Plan,
		arg.Status,
		arg.CurrentPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodEnd,
		&i.CreatedAt,
	)
	return i, err
}
